### ISSUE TITLE
Is there a file for the models?

### ISSUE THREAD

**Issue by Average-user** [ioannad/jeffrey#3]
Hi. I've trying/testing this project and it would be very helpful to have a file with the models and its details, which is consistent with `book1` and `FORMSNUM.TEX`. Since some forms have changed their meaning through time. ¿Do you happen to have one?

The files that I've found on the internet are contradictory with the data here. For example, the original `models.dat` found in [original data](https://bookstore.ams.org/surv-59), says that in permutation model N1, `11` is true but `64` false, however the table here
says that `11 -> 12 -> 336 -> 64`, which is a problem: it happens that Form 11 is not the same here as in the book (others changed as well).

I've also tried other files which I found in the internet, with all of them I get a contradiction using the `book1` file found here.

Thanks! Cool project btw.

**Comment by ioannad** [comment]
@Average-user thank you so much and I am sorry I didn't see your issue for so long! I fixed my GitHub notifications now. 

I just checked the book and indeed, the form with HR number 11 is different in the book than in the latest (2002) database that Paul Howard provided, and which cgraph uses. Here's the implication graph of the forms with the numbers you gave, includes the full statements of each form: https://cgraph.inters.co/fancy-YW39IZ14Q8UT0V941LP8RE0BUF7LM5I02KMSSQR19SXAQARRXMN4LUW6NNYNZRCOW.png  

Sadly the "Consequences of the Axiom of Choice Project" homepage is offline, but Paul Howard together with David Folk put up a [new homepage](http://104.237.130.142/consequences) as David Folk commented [here](https://mathoverflow.net/a/374183/17176). 

FWIW according to this new site, both (the current) form [11 and 64 are false in N1](http://104.237.130.142/consequences/models/Fraenkel-1).

In the new website you can get also the references to each implication, I hope that helps!

PS. The old Consequences of AC Project [website is archived here](https://web.archive.org/web/20070929131909/http://www.math.purdue.edu/~hrubin/JeanRubin/cgi-bin/conseq.html), and some but not all content is available there.

**Comment by ioannad** [comment]
For completeness, here is the list of models: http://104.237.130.142/consequences/models

I also just found the original yet updated `models.dat`, which though uses the current form numbers (the ones that cgraph uses), in Jean Rubin's archived homepage:  https://web.archive.org/web/20060901133713/http://www.math.purdue.edu/~jer/cgi-bin/models.dat

The archive seems to have captured that [changes page](https://web.archive.org/web/20071216015715/http://www.math.purdue.edu/~hrubin/JeanRubin/cgi-bin/changes.html) better, where you can find more details about how the forms changed and what reference supports what change.
