### ISSUE TITLE
Links in "The Website, aka the CGraph app" are broken

### ISSUE THREAD

**Issue by ramified** [ioannad/jeffrey#4]
Hallo! I found your database from the link "https://mathoverflow.net/questions/68442/what-could-be-some-potentially-useful-mathematical-databases", but the website is no longer available anymore. Could you please update the links? I'd be glad to hear about that! :->

**Comment by ioannad** [comment]
@ramified apologies I didn't see this earlier! The choiceless grapher is back up now: https://cgraph.inters.co
